# Generated by Django 4.2.3 on 2023-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0002_alter_sponsor_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_process", "In process"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=30,
            ),
        ),
    ]
