# Generated by Django 4.2.3 on 2023-07-12 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={"verbose_name_plural": "Universities"},
        ),
    ]
