# Generated by Django 4.2.3 on 2023-07-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0003_alter_sponsor_status"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsponsor",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="sponsor.sponsor",
            ),
        ),
    ]
